---
- name: determine if the test_db exist
  shell: ls /data/mysql/test
  register: result
  ignore_errors: True

- name: secure installation
  shell: echo -e "\nY\n123456\n123456\nY\nn\nY\nY\n" | /usr/local/mysql/bin/mysql_secure_installation
  when: result.rc == 0
